version: '3.3'

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: cpr-app
        restart: unless-stopped
        working_dir: /var/www/app
        volumes:
            - ./src:/var/www/app
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - app-network
        depends_on:
            - db
        environment:
            APP_ENV: local
            CONTAINER_ROLE: app
            SERVICE_NAME: app

    queue:
        build: .
        container_name: cpr-queue
        depends_on:
            - app
        volumes:
            - ./src:/var/www/app
        environment:
            CONTAINER_ROLE: queue
        networks:
            - app-network

    scheduler:
        build: .
        container_name: cpr-scheduler
        depends_on:
            - app
        volumes:
            - ./src:/var/www/app
        environment:
            CONTAINER_ROLE: scheduler
        networks:
            - app-network

    db:
        image: mysql:8.0
        container_name: cpr-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: app
            MYSQL_ROOT_PASSWORD: DFwe3@1xbRE2^@#
            MYSQL_USER: admin
            MYSQL_PASSWORD: DFwe3@1xbRE2^@#
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./dbdata:/var/lib/mysql
            - ./dumps:/var/dumps
            - ./docker/mysql/init:/docker-entrypoint-initdb.d
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: cpr-pma
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: db
        restart: always
        ports:
            - 8131:80
        networks:
            - app-network

    nginx:
        image: nginx:latest
        container_name: cpr-nginx
        restart: unless-stopped
        ports:
            - 8087:80
        volumes:
            - ./src:/var/www/app
            - ./docker/nginx:/etc/nginx/conf.d
            - ./docker/php/socket/:/run/php/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
